<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="robot_3r" params="parent prefix *origin">

  <!-- Robot dimensions -->
  <xacro:property name="mass" value="2" />            <!-- arbitrary value for mass -->
  <xacro:property name="base_mass" value="15" />      <!-- arbitrary value for mass -->
  <xacro:property name="base_width" value="1" />      <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="base_width_coll" value="1" /> <!-- Collision width -->
  <xacro:property name="link0_width" value="0.35" /> <!-- width of Link 1's static base -->
  <xacro:property name="link0_height" value="0.2" /> <!-- height of Link 1's static base -->
  <xacro:property name="width" value="0.05" />       <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="0.755" />    <!-- Link 1 -->
  <xacro:property name="height1_coll" value="0.755" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.5" />      <!-- Link 2 -->
  <xacro:property name="height3" value="0.5" />      <!-- Link 3 -->
  <xacro:property name="height4" value="0.35" />     <!-- Link 4 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <joint name="${prefix}base_joint" type="fixed">
    <xacro:insert_block name="origin" />
    <parent link="${parent}"/>
    <child link="${prefix}base_link" />
  </joint>

  <!-- Base Link -->
  <link name="${prefix}base_link">
    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_width} ${base_width} ${height1}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_width_coll} ${base_width_coll} ${height1_coll}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <inertia
        ixx="${base_mass / 12.0 * (base_width*base_width + height1*height1)}" ixy="0.0" ixz="0.0"
        iyy="${base_mass / 12.0 * (height1*height1 + base_width*base_width)}" iyz="0.0"
        izz="${base_mass / 12.0 * (base_width*base_width + base_width*base_width)}"/>
    </inertial>
  </link>

  <!-- Dummy Link -->
  <link name="${prefix}link0">
    <visual>
      <origin xyz="0 0 ${link0_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${link0_width} ${link0_width} ${link0_height}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${link0_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${link0_width} ${link0_width} ${link0_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${link0_height/2}" rpy="0 0 0"/>
      <mass value="${3.5 * mass}"/>
      <inertia
        ixx="${mass / 12.0 * (link0_width*link0_width + link0_height*link0_height)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (link0_height*link0_height + link0_width*link0_width)}" iyz="0.0"
        izz="${mass / 12.0 * (link0_width*link0_width + link0_width*link0_width)}"/>
    </inertial>
  </link>

  <!-- Link 1 -->
  <link name="${prefix}link1">
    <visual>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <!-- Link 2 -->
  <link name="${prefix}link2">
    <visual>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
      </inertial>
  </link>

  <!-- Link 3 -->
  <link name="${prefix}link3">
    <visual>
      <origin xyz="0 0 ${height4/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height4}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${height4/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height4}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${height4/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height4*height4)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height4*height4 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
      </inertial>
  </link>

  <!-- Tool Link -->
  <link name="${prefix}tool_link">
    <inertial>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <mass value="0.0001"/>
      <inertia
      ixx="0.001" ixy="0.0" ixz="0.0"
      iyy="0.001" iyz="0.0"
      izz="0.001"/>
    </inertial>
  </link>

  <!-- Joints -->
  <joint name="${prefix}joint1" type="revolute">
    <parent link="${prefix}link0"/>
    <child link="${prefix}link1"/>
    <origin xyz="0 0 ${link0_height}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="10" velocity="1.25"/>
  </joint>

  <joint name="${prefix}dummy_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}link0"/>
    <origin xyz="0 0 ${height1}" rpy="0 0 0"/>
  </joint>

  <joint name="${prefix}joint2" type="revolute">
    <parent link="${prefix}link1"/>
    <child link="${prefix}link2"/>
    <origin xyz="0 ${width} ${height2 - axel_offset*2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit lower="-3.14" upper="3.14" effort="10" velocity="1.25"/>
  </joint>

  <joint name="${prefix}joint3" type="revolute">
    <parent link="${prefix}link2"/>
    <child link="${prefix}link3"/>
    <origin xyz="0 ${width} ${height3 - axel_offset*2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit lower="-3.14" upper="3.14" effort="10" velocity="1.25"/>
  </joint>

  <joint name="${prefix}tool_joint" type="fixed">
    <origin xyz="0 0 ${height4 - axel_offset}" rpy="0 0 0" />
    <parent link="${prefix}link3"/>
    <child link="${prefix}tool_link" />
  </joint>

  <transmission name="joint1_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="joint2_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="joint3_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  </xacro:macro>

</robot>